Update configure

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -658,6 +658,7 @@ LIBOBJS
 qtgui_FALSE
 qtgui_TRUE
 MOC
+QT_HOST_BINS
 Qt6_LIBS
 Qt6_CFLAGS
 RENDER_EXTRA_FALSE
@@ -855,7 +856,8 @@ PKG_CONFIG_LIBDIR
 GTKGUI_BIN_CFLAGS
 GTKGUI_BIN_LIBS
 Qt6_CFLAGS
-Qt6_LIBS'
+Qt6_LIBS
+QT_HOST_BINS'
 
 
 # Initialize some variables set by options.
@@ -1550,6 +1552,8 @@ Some influential environment variables:
               linker flags for GTKGUI_BIN, overriding pkg-config
   Qt6_CFLAGS  C compiler flags for Qt6, overriding pkg-config
   Qt6_LIBS    linker flags for Qt6, overriding pkg-config
+  QT_HOST_BINS
+              value of host_bins for Qt6Core, overriding pkg-config
 
 Use these variables to override the choices made by 'configure' or to help
 it to find libraries and programs with nonstandard names/locations.
@@ -22267,6 +22271,30 @@ printf "%s\n" "yes" >&6; }
 fi
 
   # Search for moc in specific qt6 path first, then general names
+
+if test -n "$QT_HOST_BINS"; then
+    pkg_cv_QT_HOST_BINS="$QT_HOST_BINS"
+ elif test -n "$PKG_CONFIG"; then
+    if test -n "$PKG_CONFIG" && \
+    { { printf "%s\n" "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"Qt6Core\""; } >&5
+  ($PKG_CONFIG --exists --print-errors "Qt6Core") 2>&5
+  ac_status=$?
+  printf "%s\n" "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+  test $ac_status = 0; }; then
+  pkg_cv_QT_HOST_BINS=`$PKG_CONFIG --variable="host_bins" "Qt6Core" 2>/dev/null`
+		      test "x$?" != "x0" && pkg_failed=yes
+else
+  pkg_failed=yes
+fi
+ else
+    pkg_failed=untried
+fi
+QT_HOST_BINS=$pkg_cv_QT_HOST_BINS
+
+if test "x$QT_HOST_BINS" = x""
+then :
+
+fi
   for ac_prog in moc-qt6 moc
 do
   # Extract the first word of "$ac_prog", so it can be a program name with args.
@@ -22283,7 +22311,7 @@ else case e in #(
   ;;
   *)
   as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
-as_dummy="/usr/libexec/qt6:$PATH"
+as_dummy="$QT_HOST_BINS:/usr/libexec/qt6:$PATH"
 for as_dir in $as_dummy
 do
   IFS=$as_save_IFS
